# Generated by Django 3.2 on 2022-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220911_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='province',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
        migrations.AlterField(
            model_name='province',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
